### ISSUE TITLE
DownloadFileRevisited is just an assertion, right?

### ISSUE THREAD

**Issue by Oonabe** [tourdedave/elemental-selenium-tips#10]
DownloadFileRevisited for Java is just an assertion, right? Because it isn't downloading anything at all, at least not in my case.

I suppose I need to instantiate the actual download function complimentarily, but I'm a newbie into Java and Selenium so I just want to be sure I'm not missing something here.

BTW, thanks for the great job and tutorials on Selenium WebDriver,
Dave.

**Comment by tourdedave** [comment]
The code in DownloadFileRevisited is just performing a HEAD request. This doesn't download anything. You can learn more about it [here](http://elementalselenium.com/tips/8-download-a-file-revisited).
