### ISSUE TITLE
Marionette Driver instead of FirefoxDriver

### ISSUE THREAD

**Issue by rahulmr** [tourdedave/elemental-selenium-tips#13]
Hello @tourdedave is it possible to know more about marionette driver since FirefoxDriver is not working on latest Firefox version 47 and it is also said that marionette will be a standard in future?

**Comment by evanniedojadlo** [comment]
@rahulmr According to the following docs it looks like Selenium 3 uses Marionette by default when Firefox is specified: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

More information on Marionette:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette
