### ISSUE TITLE
Question - RE Ruby Updates

### ISSUE THREAD

**Issue by luke-hill** [tourdedave/elemental-selenium-tips#21]
Are you interested (More for my own improvement / getting involved more with Selenium Community), me updating some of the ruby items on here for newer rubies and using later RSpec notation on some of your earlier examples (1-20) ish.

I'm happy to do the work myself, it would be a good slow introduction into these.

**Comment by tourdedave** [comment]
Hey Luke!

Sure thing. Have at it and send me some pull requests.


Cheers,
Dave H

**Comment by luke-hill** [comment]
Ta. Have done this for the first couple. I'll close this issue off and just continue as is.
