### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by kamola** [tourdedave/elemental-selenium-tips#25]
Cannot access your website:http://elementalselenium.com/tips.
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by ckenst** [comment]
@tourdedave @kamola seems to be fine now.. But good heads up.

**Comment by tourdedave** [comment]
Thanks for the heads up!

Looks to be a memory issue in the app. Not sure what the root cause is since no changes have been shipped to the site in months. Will keep an eye on it.


Cheers,
Dave H
